apiVersion: batch/v1
kind: Job
metadata:
  name: lava-rs-server
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: lava-rs-container
          image: nvcr.io/nvidia/pytorch:24.03-py3
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -euo pipefail
              echo "=== Starting RS-LLaVA server job ==="
              cd /workspace || mkdir -p /workspace && cd /workspace

              # clone the repo you specified
              rm -rf LavaRS || true
              echo "[1] Cloning Victowolf/LavaRS ..."
              git clone https://github.com/Victowolf/LavaRS.git

              cd LavaRS || (echo "ERROR: LavaRS folder not found"; exit 1)
               # place our files into the repo (optionally copy from a configmap or mount)
              # If your CI already includes the files, skip the copy steps.

              # make sure start.sh is executable
              chmod +x start.sh || true

              echo "[4] Running start.sh ..."
              ./start.sh

              echo "=== RS-LLaVA Server Exited ==="
          resources:
            limits:
              nvidia.com/mig-3g.71gb: 1
